<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.1.2"/>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>b04dac35-eb1b-4258-b058-ef4d034fbc4e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.1.2"/>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIPromptManager\AIPromptManager.csproj" />
    <ProjectReference Include="..\PromptMaster.BackgroundProcessor\PromptMaster.BackgroundProcessor.csproj" />
  </ItemGroup>

</Project>
